{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2025-03-06T00:00:00Z",
  "bugzilla": {
    "description": "kernel: clk: mmp2: call pm_genpd_init() only after genpd.name is set",
    "id": "2350408",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2350408"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-58081",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nclk: mmp2: call pm_genpd_init() only after genpd.name is set\nSetting the genpd's struct device's name with dev_set_name() is\nhappening within pm_genpd_init(). If it remains NULL, things can blow up\nlater, such as when crafting the devfs hierarchy for the power domain:\nUnable to handle kernel NULL pointer dereference at virtual address 00000000 when read\n...\nCall trace:\nstrlen from start_creating+0x90/0x138\nstart_creating from debugfs_create_dir+0x20/0x178\ndebugfs_create_dir from genpd_debug_add.part.0+0x4c/0x144\ngenpd_debug_add.part.0 from genpd_debug_init+0x74/0x90\ngenpd_debug_init from do_one_initcall+0x5c/0x244\ndo_one_initcall from kernel_init_freeable+0x19c/0x1f4\nkernel_init_freeable from kernel_init+0x1c/0x12c\nkernel_init from ret_from_fork+0x14/0x28\nBisecting tracks this crash back to commit 899f44531fe6 (\"pmdomain: core:\nAdd GENPD_FLAG_DEV_NAME_FW flag\"), which exchanges use of genpd-\u003ename\nwith dev_name(\u0026genpd-\u003edev) in genpd_debug_add.part()."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-58081\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-58081\nhttps://lore.kernel.org/linux-cve-announce/2025030610-CVE-2024-58081-5d47@gregkh/T"
  ]
}