{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Not affected",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2024-12-27T00:00:00Z",
  "bugzilla": {
    "description": "kernel: f2fs: fix to account dirty data in __get_secs_required()",
    "id": "2334413",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2334413"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-53220",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nf2fs: fix to account dirty data in __get_secs_required()\nIt will trigger system panic w/ testcase in [1]:\n------------[ cut here ]------------\nkernel BUG at fs/f2fs/segment.c:2752!\nRIP: 0010:new_curseg+0xc81/0x2110\nCall Trace:\nf2fs_allocate_data_block+0x1c91/0x4540\ndo_write_page+0x163/0xdf0\nf2fs_outplace_write_data+0x1aa/0x340\nf2fs_do_write_data_page+0x797/0x2280\nf2fs_write_single_data_page+0x16cd/0x2190\nf2fs_write_cache_pages+0x994/0x1c80\nf2fs_write_data_pages+0x9cc/0xea0\ndo_writepages+0x194/0x7a0\nfilemap_fdatawrite_wbc+0x12b/0x1a0\n__filemap_fdatawrite_range+0xbb/0xf0\nfile_write_and_wait_range+0xa1/0x110\nf2fs_do_sync_file+0x26f/0x1c50\nf2fs_sync_file+0x12b/0x1d0\nvfs_fsync_range+0xfa/0x230\ndo_fsync+0x3d/0x80\n__x64_sys_fsync+0x37/0x50\nx64_sys_call+0x1e88/0x20d0\ndo_syscall_64+0x4b/0x110\nentry_SYSCALL_64_after_hwframe+0x76/0x7e\nThe root cause is if checkpoint_disabling and lfs_mode are both on,\nit will trigger OPU for all overwritten data, it may cost more free\nsegment than expected, so f2fs must account those data correctly to\ncalculate cosumed free segments later, and return ENOSPC earlier to\navoid run out of free segment during block allocation.\n[1] https://lore.kernel.org/fstests/20241015025106.3203676-1-chao@kernel.org/"
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-53220\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-53220\nhttps://lore.kernel.org/linux-cve-announce/2024122733-CVE-2024-53220-3664@gregkh/T"
  ]
}