{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Out of support scope",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Will not fix",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2025-02-26T00:00:00Z",
  "bugzilla": {
    "description": "kernel: ubi: ubi_create_volume: Fix use-after-free when volume creation failed",
    "id": "2347657",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2347657"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2022-49388",
  "document_distribution": "",
  "details": [
    "In the Linux kernel, the following vulnerability has been resolved:\nubi: ubi_create_volume: Fix use-after-free when volume creation failed\nThere is an use-after-free problem for 'eba_tbl' in ubi_create_volume()'s\nerror handling path:\nubi_eba_replace_table(vol, eba_tbl)\nvol-\u003eeba_tbl = tbl\nout_mapping:\nubi_eba_destroy_table(eba_tbl)   // Free 'eba_tbl'\nout_unlock:\nput_device(\u0026vol-\u003edev)\nvol_release\nkfree(tbl-\u003eentries)  // UAF\nFix it by removing redundant 'eba_tbl' releasing.\nFetch a reproducer in [Link]."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2022-49388\nhttps://nvd.nist.gov/vuln/detail/CVE-2022-49388\nhttps://lore.kernel.org/linux-cve-announce/2025022648-CVE-2022-49388-1025@gregkh/T"
  ]
}